/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Always returns 200 while the process is running.
         */
        get: operations["health_liveness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Checks that the database and Redis are reachable.
         *     Returns 200 if ready, 503 if any dependency is unavailable.
         */
        get: operations["health_readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current authenticated user + org context
         * @description Returns the resolved CurrentUser and their organization record.
         *
         *     This is the canonical first call a frontend makes after sign-in to
         *     discover the user's org UUID, role, and persona.
         */
        get: operations["get_me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get organization */
        get: operations["get_organization_v1_organizations__org_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update organization settings */
        patch: operations["update_organization_v1_organizations__org_id__patch"];
        trace?: never;
    };
    "/v1/organizations/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organization members */
        get: operations["list_members_v1_organizations__org_id__members_get"];
        put?: never;
        /** Invite a member */
        post: operations["invite_member_v1_organizations__org_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{org_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a member from the organization */
        delete: operations["remove_member_v1_organizations__org_id__members__user_id__delete"];
        options?: never;
        head?: never;
        /** Update a member's role or persona */
        patch: operations["update_member_v1_organizations__org_id__members__user_id__patch"];
        trace?: never;
    };
    "/v1/companies/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search canonical companies */
        get: operations["search_companies_v1_companies_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get enriched company profile */
        get: operations["get_company_v1_companies__company_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organization suppliers */
        get: operations["list_suppliers_v1_suppliers_get"];
        put?: never;
        /** Add a supplier to the organization */
        post: operations["create_supplier_v1_suppliers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/suppliers/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk add suppliers via CSV or JSON (async, returns job_id) */
        post: operations["bulk_create_suppliers_v1_suppliers_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/suppliers/bulk/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get bulk supplier import job status and progress */
        get: operations["get_bulk_supplier_job_v1_suppliers_bulk__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/suppliers/{supplier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get supplier details */
        get: operations["get_supplier_v1_suppliers__supplier_id__get"];
        put?: never;
        post?: never;
        /** Soft-delete supplier */
        delete: operations["delete_supplier_v1_suppliers__supplier_id__delete"];
        options?: never;
        head?: never;
        /** Update supplier attributes */
        patch: operations["update_supplier_v1_suppliers__supplier_id__patch"];
        trace?: never;
    };
    "/v1/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organization graph relationships */
        get: operations["list_relationships_v1_relationships_get"];
        put?: never;
        /** Create a graph relationship edge */
        post: operations["create_relationship_v1_relationships_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/relationships/{relationship_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get relationship details */
        get: operations["get_relationship_v1_relationships__relationship_id__get"];
        put?: never;
        post?: never;
        /** Soft-delete relationship */
        delete: operations["delete_relationship_v1_relationships__relationship_id__delete"];
        options?: never;
        head?: never;
        /** Update relationship attributes */
        patch: operations["update_relationship_v1_relationships__relationship_id__patch"];
        trace?: never;
    };
    "/v1/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get supply chain topology graph for visualization
         * @description Traverses the tenant's supply network using recursive CTE with cycle guard, depth cap (1-5), and node cap.
         */
        get: operations["get_graph_v1_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/graph/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find and explain exposure paths between entities
         * @description Traces multi-tier directed paths from an upstream company to the tenant organization or downstream target.
         */
        get: operations["get_graph_paths_v1_graph_paths_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BulkRowError */
        BulkRowError: {
            /** Row */
            row: number;
            /** Legal Name */
            legal_name?: string | null;
            /** Error */
            error: string;
        };
        /** BulkSupplierJobOut */
        BulkSupplierJobOut: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /**
             * Status
             * @description pending | processing | completed | failed
             */
            status: string;
            /**
             * Total Rows
             * @default 0
             */
            total_rows: number;
            /**
             * Processed Rows
             * @default 0
             */
            processed_rows: number;
            /**
             * Successful Rows
             * @default 0
             */
            successful_rows: number;
            /**
             * Failed Rows
             * @default 0
             */
            failed_rows: number;
            /** Errors */
            errors?: components["schemas"]["BulkRowError"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
        };
        /** CompanyAliasOut */
        CompanyAliasOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Alias */
            alias: string;
            /** Alias Norm */
            alias_norm: string;
            /** Alias Type */
            alias_type?: string | null;
            /** Source */
            source?: string | null;
            /** Confidence */
            confidence?: number | null;
        };
        /** CompanyDetailOut */
        CompanyDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Legal Name */
            legal_name: string;
            /** Name Norm */
            name_norm: string;
            /** Country */
            country?: string | null;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Legal Form */
            legal_form?: string | null;
            /** Entity Status */
            entity_status?: string | null;
            /** Primary Domain */
            primary_domain?: string | null;
            /** Industry Codes */
            industry_codes?: string[];
            /** Data Source */
            data_source?: string | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Registered Address */
            registered_address?: Record<string, never> | null;
            /** Hq Address */
            hq_address?: Record<string, never> | null;
            /** Last Enriched At */
            last_enriched_at?: string | null;
            /** Identifiers */
            identifiers?: components["schemas"]["CompanyIdentifierOut"][];
            /** Aliases */
            aliases?: components["schemas"]["CompanyAliasOut"][];
            /** Locations */
            locations?: components["schemas"]["CompanyLocationOut"][];
        };
        /** CompanyIdentifierOut */
        CompanyIdentifierOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Identifier Type */
            identifier_type: string;
            /** Identifier Value */
            identifier_value: string;
            /** Issuing Country */
            issuing_country?: string | null;
            /** Source */
            source?: string | null;
            /** Verified At */
            verified_at?: string | null;
        };
        /** CompanyLocationOut */
        CompanyLocationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Site Type */
            site_type?: string | null;
            /**
             * Is Primary
             * @default false
             */
            is_primary: boolean;
            /** Source */
            source?: string | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Valid From */
            valid_from?: string | null;
            /** Valid To */
            valid_to?: string | null;
            location: components["schemas"]["LocationOut"];
        };
        /** CompanySummaryOut */
        CompanySummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Legal Name */
            legal_name: string;
            /** Name Norm */
            name_norm: string;
            /** Country */
            country?: string | null;
            /** Jurisdiction */
            jurisdiction?: string | null;
            /** Legal Form */
            legal_form?: string | null;
            /** Entity Status */
            entity_status?: string | null;
            /** Primary Domain */
            primary_domain?: string | null;
            /** Industry Codes */
            industry_codes?: string[];
            /** Data Source */
            data_source?: string | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** GraphData */
        GraphData: {
            /** Nodes */
            nodes?: components["schemas"]["GraphNode"][];
            /** Edges */
            edges?: components["schemas"]["GraphEdge"][];
            meta: components["schemas"]["GraphMetadata"];
        };
        /** GraphEdge */
        GraphEdge: {
            /**
             * Id
             * @description Unique edge identifier
             */
            id: string;
            /**
             * Source
             * @description Source node id
             */
            source: string;
            /**
             * Target
             * @description Target node id
             */
            target: string;
            /**
             * Relationship Type
             * @description supplies_to | sub_supplies_to | owned_by | located_in
             */
            relationship_type: string;
            /** Tier */
            tier?: number | null;
            /** Criticality */
            criticality?: number | null;
            /** Annual Spend Usd */
            annual_spend_usd?: number | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Source Type
             * @description user_declared | gleif | inferred | document
             * @default user_declared
             */
            source_type: string;
            /**
             * Single Source
             * @default false
             */
            single_source: boolean;
            /** Lead Time Days */
            lead_time_days?: number | null;
        };
        /** GraphMetadata */
        GraphMetadata: {
            /** Root Id */
            root_id?: string | null;
            /**
             * Depth
             * @default 3
             */
            depth: number;
            /**
             * Node Count
             * @default 0
             */
            node_count: number;
            /**
             * Edge Count
             * @default 0
             */
            edge_count: number;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
        };
        /** GraphNode */
        GraphNode: {
            /**
             * Id
             * @description Unique node identifier for graph rendering (e.g. comp_<uuid>, org_<uuid>)
             */
            id: string;
            /**
             * Entity Id
             * @description Raw database entity UUID
             */
            entity_id?: string | null;
            /**
             * Label
             * @description Human-readable node label / legal name
             */
            label: string;
            /**
             * Type
             * @description organization | company | location
             * @default company
             */
            type: string;
            /** Country */
            country?: string | null;
            /**
             * Risk Level
             * @description CRITICAL | HIGH | MEDIUM | LOW | UNKNOWN
             * @default UNKNOWN
             */
            risk_level: string;
            /** Risk Score */
            risk_score?: number | null;
            /** Annual Spend Usd */
            annual_spend_usd?: number | null;
            /** Criticality */
            criticality?: number | null;
            /** Tier */
            tier?: number | null;
            /** Category */
            category?: string | null;
            /**
             * Single Source
             * @default false
             */
            single_source: boolean;
            /** Metadata */
            metadata?: Record<string, never>;
        };
        /** GraphPath */
        GraphPath: {
            /**
             * Nodes
             * @description Ordered sequence of nodes from source to target
             */
            nodes: components["schemas"]["GraphNode"][];
            /**
             * Edges
             * @description Ordered sequence of connecting edges
             */
            edges: components["schemas"]["GraphEdge"][];
            /**
             * Depth
             * @description Total hops in path
             */
            depth: number;
            /**
             * Path Confidence
             * @description Cumulative path confidence (product of edge confidences)
             */
            path_confidence: number;
            /**
             * Explanation
             * @description Deterministic natural explanation of the exposure connection
             */
            explanation: string;
        };
        /** GraphPathsResponse */
        GraphPathsResponse: {
            from_node?: components["schemas"]["GraphNode"] | null;
            to_node?: components["schemas"]["GraphNode"] | null;
            /** Paths */
            paths?: components["schemas"]["GraphPath"][];
            /** Summary */
            summary: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LocationOut */
        LocationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Country */
            country: string;
            /** Region */
            region?: string | null;
            /** City */
            city?: string | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Geohash */
            geohash?: string | null;
        };
        /**
         * MeOut
         * @description What GET /auth/me returns — combines the JWT principal with org context.
         */
        MeOut: {
            /** User Id */
            user_id: string;
            /** Email */
            email: string | null;
            /** Org Id */
            org_id: string | null;
            /** Clerk Org Id */
            clerk_org_id: string | null;
            /** Role */
            role: string;
            /** Persona */
            persona: string | null;
            /** Assigned Categories */
            assigned_categories: string[];
            organization: components["schemas"]["OrganizationOut"] | null;
        };
        /**
         * MemberInvite
         * @description Invite a user to an organization.
         */
        MemberInvite: {
            /**
             * User Id
             * @description Clerk user ID of the invitee
             */
            user_id: string;
            /**
             * Role
             * @description One of: org_admin, analyst, org_user, read_only
             * @default org_user
             */
            role: string;
            /**
             * Persona
             * @description UX persona hint: risk_manager, category_manager, or other
             */
            persona?: string | null;
        };
        /**
         * MemberOut
         * @description A single organization member as returned by the API.
         */
        MemberOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Id */
            user_id: string;
            /** Role */
            role: string;
            /** Persona */
            persona: string | null;
            /** Assigned Categories */
            assigned_categories: string[];
            /** Invited At */
            invited_at: string | null;
            /** Joined At */
            joined_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MemberUpdate
         * @description Update role or persona for an existing member.
         */
        MemberUpdate: {
            /** Role */
            role?: string | null;
            /** Persona */
            persona?: string | null;
            /** Assigned Categories */
            assigned_categories?: string[] | null;
        };
        /**
         * OrganizationOut
         * @description Organization record returned to clients.
         */
        OrganizationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Clerk Org Id */
            clerk_org_id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Company Id */
            company_id: string | null;
            /** Industry */
            industry: string | null;
            /** Country */
            country: string | null;
            /** Subscription Tier */
            subscription_tier: string;
            /** Monthly Token Budget */
            monthly_token_budget: number;
            /** Onboarding Completed At */
            onboarding_completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * OrganizationUpdate
         * @description Fields a caller may PATCH on an organization.
         */
        OrganizationUpdate: {
            /** Name */
            name?: string | null;
            /** Industry */
            industry?: string | null;
            /** Country */
            country?: string | null;
            /** Company Id */
            company_id?: string | null;
            /** Onboarding Completed */
            onboarding_completed?: boolean | null;
            /** Settings */
            settings?: Record<string, never> | null;
        };
        /** PaginatedCompanies */
        PaginatedCompanies: {
            /** Data */
            data: components["schemas"]["CompanySummaryOut"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /** PaginatedMembers */
        PaginatedMembers: {
            /** Data */
            data: components["schemas"]["MemberOut"][];
            /** Total */
            total: number;
        };
        /** PaginatedRelationships */
        PaginatedRelationships: {
            /** Data */
            data: components["schemas"]["RelationshipOut"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /** PaginatedSuppliers */
        PaginatedSuppliers: {
            /** Data */
            data: components["schemas"]["SupplierOut"][];
            pagination: components["schemas"]["PaginationMeta"];
        };
        /**
         * PaginationMeta
         * @description Metadata describing the pagination state.
         */
        PaginationMeta: {
            /**
             * Next Cursor
             * @description Opaque cursor token to pass to ?cursor= to fetch the next page
             */
            next_cursor?: string | null;
            /**
             * Has More
             * @description True if there are more records beyond this page
             * @default false
             */
            has_more: boolean;
            /**
             * Total
             * @description Optional total count of matching records across all pages
             */
            total?: number | null;
        };
        /** RelationshipCreate */
        RelationshipCreate: {
            /**
             * From Company Id
             * Format: uuid
             */
            from_company_id: string;
            /** To Company Id */
            to_company_id?: string | null;
            /** To Org Id */
            to_org_id?: string | null;
            /**
             * Relationship Type
             * @description supplies_to | sub_supplies_to | owned_by | located_in
             * @default supplies_to
             */
            relationship_type: string;
            /** Tier */
            tier?: number | null;
            /** Criticality */
            criticality?: number | null;
            /** Annual Spend Usd */
            annual_spend_usd?: number | null;
            /** Category */
            category?: string | null;
            /**
             * Single Source
             * @default false
             */
            single_source: boolean;
            /** Lead Time Days */
            lead_time_days?: number | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Source
             * @default user_declared
             */
            source: string;
        };
        /** RelationshipOut */
        RelationshipOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /**
             * From Company Id
             * Format: uuid
             */
            from_company_id: string;
            from_company?: components["schemas"]["CompanySummaryOut"] | null;
            /** To Company Id */
            to_company_id?: string | null;
            to_company?: components["schemas"]["CompanySummaryOut"] | null;
            /** To Org Id */
            to_org_id?: string | null;
            /** Relationship Type */
            relationship_type: string;
            /** Tier */
            tier?: number | null;
            /** Criticality */
            criticality?: number | null;
            /** Annual Spend Usd */
            annual_spend_usd?: number | null;
            /** Category */
            category?: string | null;
            /**
             * Single Source
             * @default false
             */
            single_source: boolean;
            /** Lead Time Days */
            lead_time_days?: number | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Source
             * @default user_declared
             */
            source: string;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RelationshipUpdate */
        RelationshipUpdate: {
            /** Relationship Type */
            relationship_type?: string | null;
            /** Tier */
            tier?: number | null;
            /** Criticality */
            criticality?: number | null;
            /** Annual Spend Usd */
            annual_spend_usd?: number | null;
            /** Category */
            category?: string | null;
            /** Single Source */
            single_source?: boolean | null;
            /** Lead Time Days */
            lead_time_days?: number | null;
            /** Confidence */
            confidence?: number | null;
        };
        /** SupplierCreate */
        SupplierCreate: {
            /** Company Id */
            company_id?: string | null;
            /** Legal Name */
            legal_name?: string | null;
            /** Country */
            country?: string | null;
            /** Primary Domain */
            primary_domain?: string | null;
            /**
             * Tier
             * @default 1
             */
            tier: number;
            /**
             * Criticality
             * @default 3
             */
            criticality: number;
            /** Annual Spend Usd */
            annual_spend_usd?: number | null;
            /** Category */
            category?: string | null;
            /**
             * Single Source
             * @default false
             */
            single_source: boolean;
            /** Lead Time Days */
            lead_time_days?: number | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Source
             * @default user_declared
             */
            source: string;
        };
        /** SupplierDetailOut */
        SupplierDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            company: components["schemas"]["CompanySummaryOut"];
            /** Relationship Type */
            relationship_type: string;
            /**
             * Tier
             * @default 1
             */
            tier: number | null;
            /** Criticality */
            criticality?: number | null;
            /** Annual Spend Usd */
            annual_spend_usd?: number | null;
            /** Category */
            category?: string | null;
            /**
             * Single Source
             * @default false
             */
            single_source: boolean;
            /** Lead Time Days */
            lead_time_days?: number | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Source
             * @default user_declared
             */
            source: string;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            company_detail?: components["schemas"]["CompanyDetailOut"] | null;
        };
        /** SupplierOut */
        SupplierOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            company: components["schemas"]["CompanySummaryOut"];
            /** Relationship Type */
            relationship_type: string;
            /**
             * Tier
             * @default 1
             */
            tier: number | null;
            /** Criticality */
            criticality?: number | null;
            /** Annual Spend Usd */
            annual_spend_usd?: number | null;
            /** Category */
            category?: string | null;
            /**
             * Single Source
             * @default false
             */
            single_source: boolean;
            /** Lead Time Days */
            lead_time_days?: number | null;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Source
             * @default user_declared
             */
            source: string;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SupplierUpdate */
        SupplierUpdate: {
            /** Criticality */
            criticality?: number | null;
            /** Annual Spend Usd */
            annual_spend_usd?: number | null;
            /** Category */
            category?: string | null;
            /** Tier */
            tier?: number | null;
            /** Single Source */
            single_source?: boolean | null;
            /** Lead Time Days */
            lead_time_days?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    health_readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service can accept traffic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    get_organization_v1_organizations__org_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_organization_v1_organizations__org_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_v1_organizations__org_id__members_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMembers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_member_v1_organizations__org_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberInvite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_v1_organizations__org_id__members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_v1_organizations__org_id__members__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_companies_v1_companies_search_get: {
        parameters: {
            query?: {
                /** @description Search term for company legal name */
                q?: string | null;
                /** @description 2-letter ISO country code */
                country?: string | null;
                /** @description Pagination cursor */
                cursor?: string | null;
                /** @description Page limit (max 100) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCompanies"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_v1_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suppliers_v1_suppliers_get: {
        parameters: {
            query?: {
                /** @description Filter by category */
                category?: string | null;
                /** @description Filter by criticality (1-5) */
                criticality?: number | null;
                /** @description Filter by tier */
                tier?: number | null;
                /** @description Only return active suppliers */
                active_only?: boolean;
                /** @description Pagination cursor */
                cursor?: string | null;
                /** @description Page limit (max 100) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSuppliers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_supplier_v1_suppliers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_create_suppliers_v1_suppliers_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkSupplierJobOut"];
                };
            };
        };
    };
    get_bulk_supplier_job_v1_suppliers_bulk__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkSupplierJobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_supplier_v1_suppliers__supplier_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_supplier_v1_suppliers__supplier_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_supplier_v1_suppliers__supplier_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_relationships_v1_relationships_get: {
        parameters: {
            query?: {
                /** @description Filter by relationship type */
                relationship_type?: string | null;
                /** @description Filter by source company */
                from_company_id?: string | null;
                /** @description Filter by target company */
                to_company_id?: string | null;
                /** @description Filter by tier */
                tier?: number | null;
                /** @description Only return active relationships */
                active_only?: boolean;
                /** @description Pagination cursor */
                cursor?: string | null;
                /** @description Page limit (max 100) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRelationships"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_relationship_v1_relationships_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationshipCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_relationship_v1_relationships__relationship_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relationship_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_relationship_v1_relationships__relationship_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relationship_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_relationship_v1_relationships__relationship_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                relationship_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationshipUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_v1_graph_get: {
        parameters: {
            query?: {
                /** @description Optional root company ID to center traversal around */
                root?: string | null;
                /** @description Traversal depth cap (1-5, default 3) */
                depth?: number;
                /** @description Comma-separated relationship types (e.g. supplies_to,sub_supplies_to,owned_by,located_in) */
                types?: string | null;
                /** @description Node/edge payload cap (default 300, max 5000) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_paths_v1_graph_paths_get: {
        parameters: {
            query: {
                /** @description Source company ID */
                from: string;
                /** @description Target company or org ID (defaults to org) */
                to?: string | null;
                /** @description Maximum traversal depth (1-5, default 5) */
                max_depth?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphPathsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
